### ISSUE TITLE
typerror for max_body

### ISSUE THREAD

**Issue by jincept** [akamai-open/edgegrid-curl#12]
Using dockers, I get below error:

> Traceback (most recent call last):
>   File "./egcurl", line 402, in <module>
>     sys.exit(main())
>   File "./egcurl", line 387, in main
>     config = parse_configuration(host)
>   File "./egcurl", line 335, in parse_configuration
>     config["max-body"] = int(config["max-body"])
> TypeError: int() argument must be a string or a number, not 'NoneType'
# cat ~/.egcurl

```
[default]
host:xyz.akamaiapis.net
client_token:ak...
access_token:ak...
max-body:2048
```

**Comment by elreydetodo** [comment]
The format for `~/.egcurl` calls for all the credential bits to be on one really long line. This is really just a badly explained section parsing error. This should be explained better by recent changes in the code.

Also note that I just merged pull request #19 which provides support for `~/.edgerc`. This is the INI file format supported by various other Akamai OPEN signing libraries in various languages.

I'm closing because I think this is either outright resolved or at least explained better in more recent versions.
